[versions]
agp = "8.13.0"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
kotlin = "2.2.21"
kotlixSerialization = "1.9.0"
lifecycleRuntimeKtx = "2.9.4"
material = "1.13.0"
volley = "1.2.1"

[libraries]
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlixSerialization" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
